name: "Haiku build"
on: [push, pull_request]

jobs:
  build-haiku:
    timeout-minutes: 60
    runs-on: ${{ matrix.config.runner }}
    name: build-${{ matrix.config.os }}-${{ matrix.config.version }}-${{ matrix.config.architecture }}

    strategy:
      fail-fast: false
      matrix:
        config:
          # The OS versions supported are specific to the version of the action
          # https://github.com/cross-platform-actions/action/blob/master/changelog.md
          - { os: haiku, version: 'r1beta5', runner: 'ubuntu-latest', architecture: 'x86-64' }
          - { os: haiku, version: 'hrev58647', runner: 'ubuntu-latest', architecture: 'x86-64' }

    steps:
      - uses: actions/checkout@v4

      - uses: korli/action@v0.25.0-haiku2
        with:
          operating_system: ${{ matrix.config.os }}
          version: ${{ matrix.config.version }}
          architecture: ${{ matrix.config.architecture }}
          run: >
            ssh user@localhost "pkgman update -y cmd:gcc cmd:pkg_config gcc_syslibs_devel cmd:cmake cmd:make cmd:ninja \"cmd:lrelease>=5\"
            \"devel:libboost_system>=1.69.0\" devel:libexecinfo devel:libfreetype devel:libglew devel:libgl devel:libglu
            devel:libiconv devel:libjpeg devel:liblz4 devel:liblzma devel:liblzo2 devel:libmypaint devel:libopenblas devel:libopencv_core
            devel:libpng16 devel:libsdl2_2.0 devel:libsuperlu devel:libusb_1.0 devel:libz devel:libqt5core cmd:autoconf cmd:aclocal cmd:automake cmd:libtoolize" &&

            cd thirdparty/tiff-4.0.3 && autoreconf -fi && ./configure --with-pic --disable-jbig && make -j2 &&

            cd ../../toonz &&
            
            cmake -B build -S sources -G Ninja -DWITH_TRANSLATION=OFF -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS=-DBOOST_NO_CXX11_CONSTEXPR
            -DGLUT_LIB=/system/develop/lib/libglut.so &&
            
            ninja -C build -j2
